USE [master]

CREATE DATABASE [mqttdb]

ALTER DATABASE [mqttdb] SET COMPATIBILITY_LEVEL = 110
ALTER DATABASE [mqttdb] SET ANSI_NULL_DEFAULT OFF 
ALTER DATABASE [mqttdb] SET ANSI_NULLS OFF 
ALTER DATABASE [mqttdb] SET ANSI_PADDING OFF 
ALTER DATABASE [mqttdb] SET ANSI_WARNINGS OFF 
ALTER DATABASE [mqttdb] SET ARITHABORT OFF 
ALTER DATABASE [mqttdb] SET AUTO_CLOSE OFF 
ALTER DATABASE [mqttdb] SET AUTO_CREATE_STATISTICS ON 
ALTER DATABASE [mqttdb] SET AUTO_SHRINK OFF 
ALTER DATABASE [mqttdb] SET AUTO_UPDATE_STATISTICS ON 
ALTER DATABASE [mqttdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
ALTER DATABASE [mqttdb] SET CURSOR_DEFAULT  GLOBAL 
ALTER DATABASE [mqttdb] SET CONCAT_NULL_YIELDS_NULL OFF 
ALTER DATABASE [mqttdb] SET NUMERIC_ROUNDABORT OFF 
ALTER DATABASE [mqttdb] SET QUOTED_IDENTIFIER OFF 
ALTER DATABASE [mqttdb] SET RECURSIVE_TRIGGERS OFF 
ALTER DATABASE [mqttdb] SET DISABLE_BROKER 
ALTER DATABASE [mqttdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
ALTER DATABASE [mqttdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
ALTER DATABASE [mqttdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
ALTER DATABASE [mqttdb] SET PARAMETERIZATION SIMPLE 
ALTER DATABASE [mqttdb] SET READ_COMMITTED_SNAPSHOT OFF 
ALTER DATABASE [mqttdb] SET RECOVERY SIMPLE 
ALTER DATABASE [mqttdb] SET MULTI_USER 
ALTER DATABASE [mqttdb] SET PAGE_VERIFY CHECKSUM  

GO

USE [mqttdb]

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Users] (
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[Enabled] [int] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([Id] ASC)
 WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY])

CREATE TABLE [dbo].[Connections] (
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[Server] [nvarchar](50) NOT NULL,
	[ConnectionUser] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[Port] [int] NOT NULL,
	[SSLPort] [int] NOT NULL,
	[UseSSL] [int] NOT NULL,
	[Enabled] [int] NOT NULL,
 CONSTRAINT [PK_Connections] PRIMARY KEY CLUSTERED ([Id] ASC)
 WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY])

CREATE TABLE [dbo].[Subscriptions] (
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ConnectionId] [int] NOT NULL,
	[TopicFilter] [nvarchar](255) NOT NULL,
	[QoS] [int] NOT NULL,
	[Enabled] [int] NOT NULL,
 CONSTRAINT [PK_Subscriptions] PRIMARY KEY CLUSTERED ([Id] ASC)
 WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY])

CREATE TABLE [dbo].[Topics] (
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ConnectionId] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Topics] PRIMARY KEY CLUSTERED ([Id] ASC)
 WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY])

CREATE TABLE [dbo].[Payloads] (
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TopicId] [int] NOT NULL,
	[Timestamp] [bigint] NOT NULL,
	[Data] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Payloads] PRIMARY KEY CLUSTERED ([Id] ASC)
 WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY])

ALTER TABLE [dbo].[Connections] WITH CHECK ADD CONSTRAINT [FK_Connections_Users] FOREIGN KEY([UserId]) REFERENCES [dbo].[Users] ([Id])
ALTER TABLE [dbo].[Connections] CHECK CONSTRAINT [FK_Connections_Users]

ALTER TABLE [dbo].[Subscriptions] WITH CHECK ADD CONSTRAINT [FK_Subscriptions_Connections] FOREIGN KEY([ConnectionId]) REFERENCES [dbo].[Connections] ([Id])
ALTER TABLE [dbo].[Subscriptions] CHECK CONSTRAINT [FK_Subscriptions_Connections]

ALTER TABLE [dbo].[Topics] WITH CHECK ADD CONSTRAINT [FK_Topics_Connections] FOREIGN KEY([ConnectionId]) REFERENCES [dbo].[Connections] ([Id])
ALTER TABLE [dbo].[Topics] CHECK CONSTRAINT [FK_Topics_Connections]

ALTER TABLE [dbo].[Payloads]  WITH CHECK ADD  CONSTRAINT [FK_Payloads_Topics] FOREIGN KEY([TopicId]) REFERENCES [dbo].[Topics] ([Id])
ALTER TABLE [dbo].[Payloads] CHECK CONSTRAINT [FK_Payloads_Topics]

CREATE UNIQUE NONCLUSTERED INDEX [UsersIndex] ON [dbo].[Users]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE UNIQUE NONCLUSTERED INDEX [ConnectionsIndex] ON [dbo].[Connections]
(
	[UserId] ASC,
	[Server] ASC,
	[ConnectionUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE UNIQUE NONCLUSTERED INDEX [SubscriptionsIndex] ON [dbo].[Subscriptions]
(
	[ConnectionId] ASC,
	[TopicFilter] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE UNIQUE NONCLUSTERED INDEX [TopicsIndex] ON [dbo].[Topics]
(
	[ConnectionId] ASC,
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE UNIQUE NONCLUSTERED INDEX [PayloadsIndex] ON [dbo].[Payloads]
(
	[TopicId] ASC,
	[Timestamp] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

USE [master]

ALTER DATABASE [mqttdb] SET READ_WRITE 
GO
